// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(SupportWheelOfFateDbContext))]
    [Migration("20180703191349_EngineersAndRotaEntries")]
    partial class EngineersAndRotaEntries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessLogic.DomainObjects.Engineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Engineers");

                    b.HasData(
                        new { Id = 1, FirstName = "Bradley", LastName = "Buckley" },
                        new { Id = 2, FirstName = "Melissa", LastName = "Hancock" },
                        new { Id = 3, FirstName = "Chelsea", LastName = "Davidson" },
                        new { Id = 4, FirstName = "Hayden", LastName = "Akhtar" },
                        new { Id = 5, FirstName = "Lucy", LastName = "Wade" },
                        new { Id = 6, FirstName = "James", LastName = "Harding" },
                        new { Id = 7, FirstName = "Elizabeth", LastName = "Pratt" },
                        new { Id = 8, FirstName = "Samuel", LastName = "Jenkins" },
                        new { Id = 9, FirstName = "Brian", LastName = "Shugart" },
                        new { Id = 10, FirstName = "Owen", LastName = "Stephenson" }
                    );
                });

            modelBuilder.Entity("BusinessLogic.DomainObjects.RotaEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("EngineerId");

                    b.Property<int>("HoursInShift");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId");

                    b.ToTable("RotaEntries");
                });

            modelBuilder.Entity("BusinessLogic.DomainObjects.RotaEntry", b =>
                {
                    b.HasOne("BusinessLogic.DomainObjects.Engineer", "Engineer")
                        .WithMany()
                        .HasForeignKey("EngineerId");
                });
#pragma warning restore 612, 618
        }
    }
}
